version: "3"

services:
  cognitive_project:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: cognitive_project
    environment:
      DB_URI: "mysql://root:pass_db@cognitive_project_db/prueba"
    container_name: cognitive_project
    restart: unless-stopped
    ports:
      - "5000:5000"

  cognitive_project_db:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: cognitive_project_db
    container_name: cognitive_project_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=pass_db
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
